### ISSUE TITLE
Large numbers are not shown correctly in some places

### ISSUE THREAD

**Issue by DadSchoorse** [SaschaWillems/gpuinfo.org#3] opened 2020-08-28 21:14 UTC
Example: https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxMemoryAllocationCount&platform=linux
![grafik](https://user-images.githubusercontent.com/49841484/91615226-63a58180-e983-11ea-84ea-9e75796671be.png)

It should be `4294967295` instead of `4294970000`. In other place it's `4294969856` or `4294967296`, but those aren't valid `uint32_t` values.

**Comment by ValZapod** [comment] 2021-05-26 20:36
Maybe just an overflow?

**Comment by SaschaWillems** [comment] 2021-05-26 20:37
No, that's caused by how the database engine works. I'll fix hat with some future update.

**Comment by SaschaWillems** [comment] 2022-04-30 19:39
This should be fixed by now. It was a bad combination of table datatypes and the way php handled display values.

**Closed as completed by SaschaWillems** 2022-04-30 19:39 UTC
